name: Linux

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Add bazel distribution
        run: |
          sudo apt install apt-transport-https curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

      - name: Install game dependencies
        run: |
          sudo apt update
          sudo apt install bazel libgl-dev freeglut3-dev

      - name: Build game
        run: |
          bazel build //... --config=linux -c dbg
          bazel build //... --config=linux -c opt

      - name: Build server
        run: |
          cd Server
          go mod tidy
          go build -o server.out .

# Enable when tests are created
#      - name: Run Tests | All
#        run: bazel test //...
