name: Game(Windows)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 5.4.0
      - run: bazel version

      # - name: Build game
      #   run: |
      #     bazel build //:main --config=windows-ci -c dbg
      #     bazel build //:main --config=windows-ci -c opt          
      #     bazel build //:map-editor --config=windows-ci -c dbg
      #     bazel build //:map-editor --config=windows-ci -c opt
