name: Windows

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 5.2.0
      - run: bazel version

      - name: Build Project | All
        run: |
          bazel build //:main --config=windows-ci -c dbg
          bazel build //:main --config=windows-ci -c opt          
          bazel build //:map-editor --config=windows-ci -c dbg
          bazel build //:map-editor --config=windows-ci -c opt