name: Server(Windows)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install Go protobuf
        run: |
          cd Server
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Generate Go proto files
        run: |
          $current_directory = ($pwd).path 
          $env:Path += ";$current_directory\Tools\protoc\windows"
          cd Messages
          protoc --go_out=../proto --go_opt=paths=source_relative --go-grpc_out=../proto --go-grpc_opt=paths=source_relative *.proto

      - name: Build server
        run: |
          cd Server
          go mod tidy
          go build -o server.exe .